apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "suncoder.so-academy.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: suncoder-app-service
            port:
              number: 80
  tls:
  - hosts:
    - "suncoder.so-academy.com"
    secretName: letsencrypt-tls