apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations: 
    kubernetes.io/ingress.allow-http: "true"
    cert-manager.io/issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sunny.so-academy.com
    secretName: web-ssl
  rules:
  - host: sunny.so-academy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: suncoder-app-service
            port:
              number: 80
